version: '3.4'

services:

  nginx_plus_ubuntu18.04:
    container_name: nginx-oidc-okta
    build:
      context: ./
      dockerfile: ./docker/docker-files/nginxplus-ubuntu18.04/Dockerfile
    image: nginxplus_oidc_okta_ubuntu18.04
    ports:
      - 14000:14000
    volumes:
      - type: bind
        source: ./
        target: /etc/nginx/conf.d/
      - type: bind
        source: ./docker/build-context/nginx/test/
        target: /etc/nginx/test/
      - type: bind
        source: ./docker/build-context/content
        target: /usr/share/nginx/html/
